### PR TITLE
Remove useless dependencies

### PR DESCRIPTION
**Pull request by Xiboon**

### CODE REVIEW

**Review by JelNiSlaw — APPROVED** [review]

**Comment by Indexerrowaty** [comment]
I don't think this change is good. It removes all vulnerabilities that are shown when installing dependencies.
image
The more vulnerabilities the better.

**Comment by JelNiSlaw** [comment]
maybe yo u  bad computor your need fix

**Comment by JelNiSlaw** [comment]
my is good it work i 20 vulnarbietes

**Comment by Indexerrowaty** [comment]
> maybe yo u bad computor your need fix

no my computer is gud. i'm have intel sd graphic 69 and intel pentium processor

**Comment by Indexerrowaty** [comment]
and operating system Windows XP sp3

**Comment by Xiboon** [comment]
pobrane (1)

**Pull request closed without merging**
